Implementation
GlebKirsan/go_final_project pull request #2
Opened 2024-08-06 12:15 UTC by GlebKirsan

2024-08-06 20:20 UTC, dirtymew requested changes
Привет Глеб

очень крутая работа - почти нет вопросов
 - логирование
 - make
 - миграции
 - структура проекта
 - архитектура(тут можно было еще интерфесы добавить чтобы связность снизить)
 - документация
 - хороший читаемый код

есть пару мелочей которые стоит поправить

Спасибо получил удовольствие...

ты задание со звездочкой доделывать будешь ?

2024-08-06 20:20 UTC, dirtymew commented on cmd/task-tracker/main.go
> +
что-то с группировкой импортов - нужно поправить везде

используй go imports

2024-08-06 20:20 UTC, dirtymew commented on Makefile
> +	go run ./...
а почему запускаешь через go run а не собраный бинарник?

2024-08-06 20:20 UTC, dirtymew commented on Makefile
> +
make отлично

2024-08-06 20:20 UTC, dirtymew commented on internal/database/database.go
> +	if err = runMigration(db); err != nil {
миграции - тоже супер

2024-08-06 20:20 UTC, dirtymew commented on cmd/task-tracker/main.go
> +	logger := logger.Get()
отлично что добавил логирование

2024-08-06 20:20 UTC, dirtymew commented on internal/database/repositories/task.go
> +func (repo *TaskRepo) UpdateTask(task *models.Task) error {
название не консистентное - Update

2024-08-06 20:20 UTC, dirtymew commented on internal/database/repositories/task.go
> +func (repo *TaskRepo) GetTask(id int64) (*models.Task, error) {
Get

2024-08-06 20:20 UTC, dirtymew commented on internal/database/repositories/task.go
> +func (repo *TaskRepo) GetAll() ([]models.Task, error) {
ну тут я бы упростил и сделал один метод

FInd(filter stirng) - что-то такое

2024-08-08 15:07 UTC, GlebKirsan commented on cmd/task-tracker/main.go
> +
Поправил.

2024-08-08 15:07 UTC, GlebKirsan commented on Makefile
> +	go run ./...
Поменял, теперь используется собранный бинарник.

2024-08-08 15:08 UTC, GlebKirsan commented on internal/database/repositories/task.go
> +func (repo *TaskRepo) UpdateTask(task *models.Task) error {
Исправил.

2024-08-08 15:08 UTC, GlebKirsan commented on internal/database/repositories/task.go
> +func (repo *TaskRepo) GetAll() ([]models.Task, error) {
Поправил, сделал один метод, но, возможно, не так понял, пришлось перенести логику обработки фильтра в репозиторий.

2024-08-08 15:09 UTC, GlebKirsan commented
> Привет Глеб
> 
> очень крутая работа - почти нет вопросов
> 
> * логирование
> * make
> * миграции
> * структура проекта
> * архитектура(тут можно было еще интерфесы добавить чтобы связность снизить)
> * документация
> * хороший читаемый код
> 
> есть пару мелочей которые стоит поправить
> 
> Спасибо получил удовольствие...
> 
> ты задание со звездочкой доделывать будешь ?

Большое спасибо! Задание со звёздочкой доделал.

2024-08-08 17:09 UTC, dirtymew approved these changes
Привет Глеб

все супер 

Поздравляю и желаю удачи

2024-08-08 17:09 UTC, dirtymew commented on internal/database/repositories/task.go
> +	query.WriteString("SELECT id, date, title, comment, repeat FROM scheduler")
можно было вспомогательную функцию обьявить типа getQuery(filter stirng) 
и там из фильтра по switch вернуть уже готовы запрос 

так функцию стораджда разгрузишь

2024-08-08 17:09 UTC, dirtymew commented on internal/database/repositories/task_queries.go
> +const update = `
не очень удобно лучше по месту запросы писать - ну это на мой взгляд

2024-08-08 17:09 UTC, dirtymew commented on internal/database/repositories/task.go
> +			query.WriteString(" WHERE title LIKE CONCAT('%', :title, '%')")
тут по заданию еще в комменте искать надо - обрати внимание - не буде возвращать за такое работу

2024-08-23 07:20 UTC, merged